### ISSUE TITLE
confusing examples

### ISSUE THREAD

**Issue by katreesedarcene** [learn-co-curriculum/sql-join-tables-readme#10]
I think these examples have been what has thrown me off in the previous lessons.   Let's confirm that worked by checking our schema:

sqlite3> .schema
CREATE TABLE cats (
id INTEGER PRIMARY KEY, 
name TEXT, 
age INTEGER,
breed TEXT);
 
CREATE TABLE owners (id INTEGER PRIMARY KEY, name TEXT);
 
CREATE TABLE cats_owners (
cat_id INTEGER,
owner_id INTEGER
);
 It looks like you copy and paste the whole thing as opposed to just typing in .schema then the results will look like the latter part. I think having it separate in all examples especially some of the earlier lessons will help with understanding

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
