### ISSUE TITLE
Insert data missing ID

### ISSUE THREAD

**Issue by joshuaneedham** [learn-co-curriculum/sql-join-tables-readme#8]
The instructions for inserting data into the DB on this particular exercise are missing the ID portion of the schema.

**INSERT DATA**
`
INSERT INTO owners (name) VALUES ("mugumogu");
INSERT INTO owners (name) VALUES ("Sophie");
INSERT INTO owners (name) VALUES ("Penny");
INSERT INTO cats (name, age, breed) VALUES ("Maru", 3, "Scottish Fold");
INSERT INTO cats (name, age, breed) VALUES ("Hana", 3, "Tabby");
INSERT INTO cats (name, age, breed) VALUES ("Nona", 4, "Tortoiseshell" );
INSERT INTO cats (name, age, breed) VALUES ("Lil' Bub", 2, "perma-kitten");
`

This causes the future instructions to not produce the correct information. Maybe this is by design but when you get towards the bottom of the exercise the queries don't work because there are no ID's(primary keys) associated with the 'owners' or the 'cats'.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
